build:
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'

      dependencies:
        before:
          - composer install --no-interaction --prefer-dist

      tests:
        override:
          - vendor/bin/phpunit --colors=always
          - vendor/bin/phpstan analyse --no-progress --memory-limit=1G
          - vendor/bin/psalm --output-format=console
          - vendor/bin/pint --test
          - vendor/bin/phpmetrics --report-html=build/phpmetrics src

filter:
  excluded_paths:
    - 'tests/*'

checks:
  php: true
coding_style:
    php: {}