build:
  environment:
    php:
      version: '8.4'

  dependencies:
    before:
      - composer install --no-interaction --prefer-dist

  tests:
    override:
      - command: vendor/bin/phpunit
      - command: vendor/bin/phpstan analyse --no-progress --memory-limit=1G
      - command: vendor/bin/psalm --output-format=console
      - command: vendor/bin/pint --test

filter:
  paths:
    - src/*
    - app/*
    - tests/*
