checks:
  php: true

filter:
  paths:
    - src/
    - app/
  excluded_paths:
    - tests/
    - vendor/
  dependency_paths:
    - vendor/

build:
  image: default-bionic

  environment:
    php:
      version: 8.3
      ini:
        xdebug.mode: coverage,develop
        memory_limit: -1

  nodes:
    analysis:
      dependencies:
        before:
          - composer self-update
          - composer install --no-interaction --prefer-dist

      tests:
        override:
          - command: vendor/bin/phpunit --colors=always --coverage-clover=coverage.xml
            coverage:
              file: coverage.xml
              format: php-clover
          - command: vendor/bin/phpstan analyse --no-progress --memory-limit=1G
          - command: vendor/bin/psalm --output-format=console
          - command: vendor/bin/pint --test
